# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties (Minecraft 1.21.11 - the last "1.x" release, before the 26.x versions)
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=me.midwu
archives_base_name=guitoxaero
# Dependencies
fabric_version=0.141.6+1.21.11
